feat: create github-workflow and update docs
Signed-off-by: duttarnab <arnab.bdutta@gmail.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -685,3 +685,62 @@ jobs:
           if [ -n "$FILE_LIB" ]; then
             gh release upload "${VERSION}" $FILE_LIB $FILE_LIB.sha256sum $FILE_LIB.asc
           fi
+  build_cedarling_uniffi:
+    if: github.repository == 'JanssenProject/jans'
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Harden Runner
+      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+      with:
+        egress-policy: audit
+
+    - name: Checkout
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+    - name: Import GPG key
+      id: import_gpg
+      continue-on-error: true
+      uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
+      with:
+        gpg_private_key: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY }}
+        passphrase: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY_PASSPHRASE }}
+        git_user_signingkey: true
+        git_commit_gpgsign: true
+    - name: Build and release cedarling uniffi build in linux
+      working-directory: ${{ github.workspace }}/jans-cedarling/bindings/cedarling_uniffi
+      run: |
+        rustup update stable && rustup default stable
+        TAG=$(echo ${{ github.event.ref }} | cut -d '/' -f 3 | sed 's/^v//')
+        VERSION="$(echo ${{ github.event.ref }} | cut -d '/' -f 3)"
+        if [ "${TAG}" == "nightly" ]; then
+          VERSION=nightly
+          TAG="0.0.0"
+        fi
+        cargo build -r -p cedarling_uniffi
+        cp ../../target/release/libcedarling_uniffi.so libcedarling_uniffi-${TAG}.so
+        FILE="libcedarling_uniffi-${TAG}.so"
+        sha256sum $FILE >> $FILE.sha256sum
+        gpg --armor --detach-sign $FILE || echo "Failed to sign"
+        gpg --armor --detach-sign $FILE.sha256sum || echo "Failed to sign"
+
+        echo "${{ secrets.MOAUTO_WORKFLOW_TOKEN }}" | gh auth login --with-token
+        gh release upload "${VERSION}" $FILE $FILE.sha256sum $FILE.asc
+    - name: Build kotlin binding in linux
+      working-directory: ${{ github.workspace }}/jans-cedarling/bindings/cedarling_uniffi
+      run: |
+        rustup update stable && rustup default stable
+        TAG=$(echo ${{ github.event.ref }} | cut -d '/' -f 3 | sed 's/^v//')
+        VERSION="$(echo ${{ github.event.ref }} | cut -d '/' -f 3)"
+        if [ "${TAG}" == "nightly" ]; then
+          VERSION=nightly
+          TAG="0.0.0"
+        fi
+        cargo build -r -p cedarling_uniffi
+        cargo run --bin uniffi-bindgen generate --library ${{ github.workspace }}/jans-cedarling/target/release/libcedarling_uniffi.so --language kotlin --out-dir ./
+        mv cedarling_uniffi.kt cedarling_uniffi-${TAG}.kt
+        FILE="cedarling_uniffi-${TAG}.kt"
+        sha256sum $FILE >> $FILE.sha256sum
+        gpg --armor --detach-sign $FILE || echo "Failed to sign"
+        gpg --armor --detach-sign $FILE.sha256sum || echo "Failed to sign"
+
+        echo "${{ secrets.MOAUTO_WORKFLOW_TOKEN }}" | gh auth login --with-token
+        gh release upload "${VERSION}" $FILE $FILE.sha256sum $FILE.asc
