ci: fix  version when there is no nightly version
Signed-off-by: moabu <47318409+moabu@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -22,7 +22,7 @@ jobs:
             build_files: deb/noble
             asset_prefix: '_'
             asset_path: jans
-            sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
+            sign_cmd: debsig-signer -k DE92BEF14A1A4E542F678B64DC3C790386C73900
             python_version: 3.11
           - name: ubuntu22
             os: ubuntu-20.04
@@ -78,7 +78,7 @@ jobs:
          sudo apt-get update
          sudo apt-get install -y python${{ matrix.python_version }}
          sudo apt install -y build-essential devscripts debhelper rpm python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib
-         sudo apt install -y dpkg-sig python3-crypto python3-distutils || echo "failed to install some python packages"
+         sudo apt install -y dpkg-sig python3-crypto python3-distutils ||  sudo apt install -y debsig-verify debsig-append debsig-signer
          sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
          sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2 || echo "failed to install psycopg2"
     - name: Import GPG key
@@ -446,8 +446,11 @@ jobs:
         if [ "${TAG}" == "nightly" ]; then
           NPM_TAG=nightly
           TAG="0.0.0"
-          LAST_NIGHTLY_NPM_VERSION=$(npm dist-tag ls cedarling_wasm | grep nightly | awk '{print $2}' | sort -V | tail -n 1) || LAST_NIGHTLY_NPM_VERSION=0.0.0  
+          LAST_NIGHTLY_NPM_VERSION=$(npm dist-tag ls cedarling_wasm | grep nightly | awk '{print $2}' | sort -V | tail -n 1) || echo "Failed to get last nightly version"
           NEW_NPM_VERSION=$(echo $LAST_NIGHTLY_NPM_VERSION | awk -F. '{print $1"."$2"."$3+1}')
+          if [ "${NEW_NPM_VERSION}" == "..1" ]; then
+              NEW_NPM_VERSION="0.0.0"
+          fi
           sed -i "s/^version = \".*\"/version = \"${NEW_NPM_VERSION}\"/" Cargo.toml
           echo "Replaced  $NEW_NPM_VERSION in Cargo.toml"
         fi
