ci(jans-cedarling): add go binding to linux release
Signed-off-by: SafinWasi <6601566+SafinWasi@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -543,3 +543,43 @@ jobs:
         gpg --armor --detach-sign cedarling-krakend-arm64-"${{ env.KRAKEND_BUILDER_IMAGE }}"-"${{ env.TAG }}".so || echo "Failed to sign"
         echo "${{ secrets.MOAUTO_WORKFLOW_TOKEN }}" | gh auth login --with-token
         gh release upload "${{ env.VERSION }}" *.so *.sha256sum *.asc
+  build_cedarling_go:
+    if: github.repository == 'JanssenProject/jans'
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Install Golang dependencies
+        uses: actions/setup-go@v5
+        with:
+            go-version: '1.24'
+      - name: Build rust artifacts
+        working-directory: ${{ github.workspace }}/jans-cedarling/bindings/cedarling_go
+        run: |
+          sudo apt install rustup
+          rustup update stable && rustup default stable
+          TAG=$(echo ${{ github.event.ref }} | cut -d '/' -f 3 | sed 's/^v//')
+          VERSION="$(echo ${{ github.event.ref }} | cut -d '/' -f 3)"
+          if [ "${TAG}" == "nightly" ]; then
+            VERSION=nightly
+            TAG="0.0.0"
+          fi
+          cargo build -r -p cedarling_go
+          cp ../../target/release/libcedarling_go.so libcedarling_go-${TAG}.so
+      - name: Generate sha256sum and sign
+        working-directory: ${{ github.workspace }}/jans-cedarling/bindings/cedarling_go
+        run: |
+          TAG=$(echo ${{ github.event.ref }} | cut -d '/' -f 3 | sed 's/^v//')
+          VERSION="$(echo ${{ github.event.ref }} | cut -d '/' -f 3)"
+          if [ "${TAG}" == "nightly" ]; then
+            VERSION=nightly
+            TAG="0.0.0"
+          fi
+          sha256sum libcedarling_go-${TAG}.so >> libcedarling_go-${TAG}.so.sha256sum 
+          gpg --armor --detach-sign libcedarling_go-${TAG}.so || echo "Failed to sign"
+          gpg --armor --detach-sign libcedarling_go-${TAG}.so.sha256sum || echo "Failed to sign"
+          echo "${{ secrets.MOAUTO_WORKFLOW_TOKEN }}" | gh auth login --with-token
+          gh release upload "${{ env.VERSION }}" *.so *.sha256sum *.asc
