ci: output log on fails
Signed-off-by: moabu <47318409+moabu@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -22,7 +22,7 @@ jobs:
             build_files: deb/noble
             asset_prefix: '_'
             asset_path: jans
-            sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
+            sign_cmd: debsigs --sign=origin -k DE92BEF14A1A4E542F678B64DC3C790386C73900
             python_version: 3.11
           - name: ubuntu22
             os: ubuntu-20.04
@@ -452,9 +452,9 @@ jobs:
           echo "Replaced  $NEW_NPM_VERSION in Cargo.toml"
         fi
         wasm-pack build --release --target web --scope janssenproject
-        wasm-pack login
+        wasm-pack logout && wasm-pack login || echo "Failed to login"
         cd pkg
-        npm publish --access=public --tag "${NPM_TAG}"
+        npm publish --access=public --tag "${NPM_TAG}" || cat $(ls -t /home/runner/.npm/_logs/*-debug-0.log | head -n 1)
 
     - name: Archive and sign pkg contents
       id: archive_pkg
