ci: fix  version when there is no nightly version
Signed-off-by: moabu <47318409+moabu@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -78,8 +78,9 @@ jobs:
          sudo apt-get update
          sudo apt-get install -y python${{ matrix.python_version }}
          sudo apt install -y build-essential devscripts debhelper rpm python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib
+         sudo apt install -y dpkg-sig python3-crypto python3-distutils || echo "failed to install some python packages"
          sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
-         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2
+         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2 || echo "failed to install psycopg2"
     - name: Import GPG key
       id: import_gpg
       continue-on-error: true
@@ -445,7 +446,7 @@ jobs:
         if [ "${TAG}" == "nightly" ]; then
           NPM_TAG=nightly
           TAG="0.0.0"
-          LAST_NIGHTLY_NPM_VERSION=$(npm dist-tag ls cedarling_wasm | grep nightly | awk '{print $2}' | sort -V | tail -n 1 || echo "0.0.0")
+          LAST_NIGHTLY_NPM_VERSION=$(npm dist-tag ls cedarling_wasm | grep nightly | awk '{print $2}' | sort -V | tail -n 1) || LAST_NIGHTLY_NPM_VERSION=0.0.0  
           NEW_NPM_VERSION=$(echo $LAST_NIGHTLY_NPM_VERSION | awk -F. '{print $1"."$2"."$3+1}')
           sed -i "s/^version = \".*\"/version = \"${NEW_NPM_VERSION}\"/" Cargo.toml
           echo "Replaced  $NEW_NPM_VERSION in Cargo.toml"
