ci: skip if the version exists already in npm registery
Signed-off-by: moabu <47318409+moabu@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -443,7 +443,9 @@ jobs:
         tar -czvf cedarling_wasm_"${TAG}"_pkg.tar.gz -C pkg .
         gpg --armor --detach-sign cedarling_wasm_"${TAG}"_pkg.tar.gz || echo "Failed to sign"
         echo "${{ secrets.MOAUTO_WORKFLOW_TOKEN }}" | gh auth login --with-token
-        gh release upload "${VERSION}" *.tar.gz *.asc
+        gh release upload "${VERSION}" *.tar.gz *.asc --clobber || {
+          echo "gh release upload failed (assets may already exist), continuing..."
+        }
 
   build_demo_packages:
     if: |
