ci(mysql): run mysql setup

diff --git a/.github/workflows/microk8s_mysql.yml b/.github/workflows/microk8s_mysql.yml
--- a/.github/workflows/microk8s_mysql.yml
+++ b/.github/workflows/microk8s_mysql.yml
@@ -24,9 +24,8 @@ jobs:
         ip=$(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
         echo "::set-output name=ip::$ip"
         sudo snap install microk8s --classic
-        sudo snap alias microk8s.kubectl kubectl
-        sudo microk8s.status --wait-ready
-        sudo microk8s.enable dns registry ingress
+        sudo microk8s status --wait-ready
+        sudo microk8s enable dns registry ingress
 
     - name: Install helm
       run: |
@@ -37,27 +36,33 @@ jobs:
 
     - name: Install mysql
       run: |
-        wget https://raw.githubusercontent.com/mo-auto/scripts/main/set_microk8s_kube_config.py && chmod u+x set_microk8s_kube_config.py && sudo python3 ./set_microk8s_kube_config.py
-        sudo helm repo add bitnami https://charts.bitnami.com/bitnami
-        sudo microk8s.kubectl get po
-        sudo helm install my-release --set auth.rootPassword=Test1234#,auth.database=jans bitnami/mysql
-        sudo microk8s. kubectl get po
-        sudo microk8s.kubectl wait -n default --for=condition=ready pod --timeout=300s -l statefulset.kubernetes.io/pod-name=my-release-mysql-0 || echo "Not Found"
+        sudo microk8s config > config
+        sudo microk8s kubectl create ns jans --kubeconfig="$PWD/config"
+        sudo microk8s kubectl apply -f https://raw.githubusercontent.com/mo-auto/scripts/main/yamls/quickmysql.yaml -n jans
+        sudo microk8s kubectl get po --kubeconfig="$PWD/config" -n jans|| echo "Not Found"
+        sudo microk8s kubectl wait --for=condition=available --timeout=300s deploy/mysql --kubeconfig="$PWD/config" -n jans || sudo microk8s kubectl logs -l app=mysql -c mysql  --kubeconfig="$PWD/config" || echo "Not Found"
+        sleep 30
+        sudo microk8s kubectl get po --kubeconfig="$PWD/config" -n jans || echo "Not Found"
+        sleep 30
+        sudo microk8s kubectl logs -l app=mysql -c mysql  --kubeconfig="$PWD/config" -n jans|| sleep 30 || echo "Not Found"
+        sudo microk8s kubectl describe po -l app=mysql -n jans || sleep 30 || echo "Not Found"
 
     - name: Test Janssen authorization server with mysql backend
       id: test_kubernetes
       run: |
-          sudo microk8s.kubectl create ns jans
-          sudo microk8s.kubectl get po
-          sudo helm install jans -f charts/jans/values.yaml charts/jans -n jans --set global.lbIp=${{ steps.microk8s.outputs.ip }} --set global.provisioner="microk8s.io/hostpath" --set global.cnPersistenceType="sql" --set global.cnPersistenceType="sql" --set config.configmap.cnSqlDbUser="root"
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config"
+          sudo helm install jans -f charts/jans/values.yaml charts/jans -n jans --set global.lbIp=${{ steps.microk8s.outputs.ip }} --set global.provisioner="microk8s.io/hostpath" --set global.cnPersistenceType="sql" --set global.cnPersistenceType="sql" --set config.configmap.cnSqlDbUser="root" --set config.configmap.cnSqlDbHost="mysql.jans.svc" --set config.configmap.cnSqlDbName="mysql" --kubeconfig="$PWD/config"
           sleep 30
-          sudo microk8s.kubectl get po -n jans
-          sudo microk8s.kubectl -n jans wait --for=condition=available --timeout=600s deploy/jans-auth-server || sudo kubectl logs -l APP_NAME=auth-server -c jans-auth-server -n jans || echo "Not Found"
-          sudo microk8s.kubectl get po -n jans
-          sudo microk8s.kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-client-api || sudo kubectl logs -l APP_NAME=client-api -c jans-client-api -n jans || echo "Not Found"
-          sudo microk8s.kubectl get po -n jans
-          sudo microk8s.kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-fido2 || sudo kubectl logs -l APP_NAME=fido2 -c jans-fido2 -n jans || echo "Not Found"
-          sudo microk8s.kubectl get po -n jans
-          sudo microk8s.kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-scim || sudo kubectl logs -l APP_NAME=scim -c jans-scim -n jans || echo "Not Found"
-          sudo microk8s.kubectl get po -n jans
-
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config"
+          sudo microk8s kubectl -n jans wait --for=condition=available --timeout=600s deploy/jans-auth-server --kubeconfig="$PWD/config" || sudo microk8s kubectl logs -l APP_NAME=auth-server -c auth-server -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl logs -l APP_NAME=persistence-loader -c persistence -n jans --kubeconfig="$PWD/config"
+          sudo microk8s kubectl get po --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-client-api --kubeconfig="$PWD/config" || sudo microk8s kubectl logs -l APP_NAME=client-api -c client-api -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl logs -l APP_NAME=persistence-loader -c persistence -n jans --kubeconfig="$PWD/config"
+          sudo microk8s kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-fido2 --kubeconfig="$PWD/config" || sudo microk8s kubectl logs -l APP_NAME=fido2 -c fido2 -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl logs -l APP_NAME=persistence-loader -c persistence -n jans --kubeconfig="$PWD/config"
+          sudo microk8s kubectl -n jans wait --for=condition=available --timeout=300s deploy/jans-scim --kubeconfig="$PWD/config" || sudo microk8s kubectl logs -l APP_NAME=scim -c scim -n jans --kubeconfig="$PWD/config" || echo "Not Found"
+          sudo microk8s kubectl get po -n jans --kubeconfig="$PWD/config" || echo "Not Found"
