feat(ci): add c bindings test

diff --git a/.github/workflows/test-cedarling.yml b/.github/workflows/test-cedarling.yml
--- a/.github/workflows/test-cedarling.yml
+++ b/.github/workflows/test-cedarling.yml
@@ -1,4 +1,4 @@
-name: Cedarling Testcases 
+name: Cedarling Testcases
 
 on:
   pull_request:
@@ -13,96 +13,124 @@ jobs:
   rust_tests:
     runs-on: ubuntu-latest
     steps:
-    - name: Harden Runner
-      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
-      with:
-        egress-policy: audit
-    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-    - name: Install Rust
-      uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
-    - name: Run Tests
-      working-directory: jans-cedarling
-      run: |
-        cargo test --workspace
-    - name: Run Clippy on native target
-      working-directory: jans-cedarling
-      run: |
-        rustup component add clippy
-        cargo clippy -- -Dwarnings
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
+      - name: Run Tests
+        working-directory: jans-cedarling
+        run: |
+          cargo test --workspace
+      - name: Run Clippy on native target
+        working-directory: jans-cedarling
+        run: |
+          rustup component add clippy
+          cargo clippy -- -Dwarnings
   wasm_tests:
     runs-on: ubuntu-latest
     steps:
-    - name: Harden Runner
-      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
-      with:
-        egress-policy: audit
-    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-    - name: Install Rust
-      uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
-    - name: Install WASM dependencies
-      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
-    - name: Run WASM tests using chrome
-      working-directory: jans-cedarling/bindings/cedarling_wasm
-      run: |
-        wasm-pack test --headless --chrome
-    - name: Run WASM tests using firefox
-      working-directory: jans-cedarling/bindings/cedarling_wasm
-      run: |
-        wasm-pack test --headless --firefox
-    - name: Run Clippy on WASM target
-      working-directory: jans-cedarling
-      run: |
-        rustup component add clippy
-        cargo clippy --target wasm32-unknown-unknown -- -Dwarnings
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
+      - name: Install WASM dependencies
+        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
+      - name: Run WASM tests using chrome
+        working-directory: jans-cedarling/bindings/cedarling_wasm
+        run: |
+          wasm-pack test --headless --chrome
+      - name: Run WASM tests using firefox
+        working-directory: jans-cedarling/bindings/cedarling_wasm
+        run: |
+          wasm-pack test --headless --firefox
+      - name: Run Clippy on WASM target
+        working-directory: jans-cedarling
+        run: |
+          rustup component add clippy
+          cargo clippy --target wasm32-unknown-unknown -- -Dwarnings
   python_tests:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: ["3.10", "3.11"]
     steps:
-    - name: Harden Runner
-      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
-      with:
-        egress-policy: audit
-    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python3 -m pip install --upgrade pip || echo "Failed to upgrade pip"
-        python3 -m pip install tox
-    - name: Test with pytest
-      working-directory: jans-cedarling/bindings/cedarling_python
-      run: |
-        tox
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python3 -m pip install --upgrade pip || echo "Failed to upgrade pip"
+          python3 -m pip install tox
+      - name: Test with pytest
+        working-directory: jans-cedarling/bindings/cedarling_python
+        run: |
+          tox
   golang_tests:
     runs-on: ubuntu-latest
     steps:
-    - name: Harden Runner
-      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
-      with:
-        egress-policy: audit
-    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-    - name: Install Rust
-      uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
-    - name: Install Golang dependencies
-      uses: actions/setup-go@v5
-      with:
-          go-version: '1.24'
-    - name: Run build rust artifacts
-      working-directory: jans-cedarling/bindings/cedarling_go
-      run: |
-        rustup component add clippy
-        cargo build -r -p cedarling_go
-        cp "../../target/release/libcedarling_go.so" "."
-    - name: Install Go dependencies
-      working-directory: jans-cedarling/bindings/cedarling_go
-      run: |
-        go mod download && go mod tidy
-    - name: Run golang tests
-      working-directory: jans-cedarling/bindings/cedarling_go
-      run: |
-        export LD_LIBRARY_PATH="$(pwd):${LD_LIBRARY_PATH}"
-        go test .
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
+      - name: Install Golang dependencies
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.24"
+      - name: Run build rust artifacts
+        working-directory: jans-cedarling/bindings/cedarling_go
+        run: |
+          rustup component add clippy
+          cargo build -r -p cedarling_go
+          cp "../../target/release/libcedarling_go.so" "."
+      - name: Install Go dependencies
+        working-directory: jans-cedarling/bindings/cedarling_go
+        run: |
+          go mod download && go mod tidy
+      - name: Run golang tests
+        working-directory: jans-cedarling/bindings/cedarling_go
+        run: |
+          export LD_LIBRARY_PATH="$(pwd):${LD_LIBRARY_PATH}"
+          go test .
+  c_tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
+        with:
+          egress-policy: audit
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Install build dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y build-essential
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
+      - name: Build Rust C library
+        working-directory: jans-cedarling/bindings/cedarling_c
+        run: |
+          cargo build --release
+      - name: Build and run C example
+        working-directory: jans-cedarling/bindings/cedarling_c/examples
+        run: |
+          make
+          LD_LIBRARY_PATH=../target/release ./basic_example
+      - name: Build and run C tests
+        working-directory: jans-cedarling/bindings/cedarling_c/tests
+        run: |
+          make
+          LD_LIBRARY_PATH=../target/release ./test_cedarling
